Testing phase1-b

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -33,13 +33,11 @@ jobs:
           echo "Running validation because 'full validation' label was added"
           # Add your validation logic here (e.g., linting, testing)
 
-  remove-label:
-    needs: validate
-    if: always()  # Ensures this runs even if validation fails
-    runs-on: ubuntu-latest
+          # Simulate failure
+          exit 1
 
-    steps:
       - name: Remove 'needs-validation' label
+        if: always()
         run: |
           PR_NUMBER=${{ github.event.pull_request.number }}
           REPO=${{ github.repository }}
@@ -51,3 +49,22 @@ jobs:
           curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels/${ENCODED_LABEL}"
+
+#   remove-label:
+#     needs: validate
+#     if: always()  # Ensures this runs even if validation fails
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Remove 'needs-validation' label
+#         run: |
+#           PR_NUMBER=${{ github.event.pull_request.number }}
+#           REPO=${{ github.repository }}
+#           LABEL="full validation"
+#           ENCODED_LABEL=$(printf "%s" "$LABEL" | sed -e 's/ /%20/g' -e 's/:/%3A/g' -e 's/\//%2F/g' -e 's/?/%3F/g' -e 's/&/%26/g' -e 's/=/%3D/g')
+
+#           echo $ENCODED_LABEL
+#           echo "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels/$ENCODED_LABEL"
+#           curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+#               -H "Accept: application/vnd.github.v3+json" \
+#                "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels/${ENCODED_LABEL}"
